import type { Metadata } from "next";
import { Lora, Arsenal } from "next/font/google";
import "./globals.css";

const lora = Lora({ subsets: ["latin"] });
const arsenal = Arsenal({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Terre",
    description: "Generated by create next app",
};

const bodyStyles = `${lora.className} ${arsenal.className} min-w-[300px]`;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={bodyStyles}>{children}</body>
        </html>
    );
}
